import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Card from "../components/Card";
import { useSession } from "next-auth/react";
import Footer from "../components/Footer";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Voting Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container flex flex-col justify-center items-center mx-auto pt-32 pb-8 w-full">
        <Header />
        {session && <Card />}
      </div>
      <Footer />
    </>
  );
}
